/**
 * Rebuilds a `CREATE TABLE` for a live Postgres table.
 *
 * Postgres has no `SHOW CREATE TABLE`, so "copy the create statement" has to be
 * assembled from the catalogue. This works from a `TableDefinition` — what the
 * driver already fetched — which is a different job from the table designer's
 * generator, which works from unsaved editor state and also has to diff.
 */

import { postgresDialect as d, qualify } from './dialect'
import type { ColumnInfo, TableDefinition } from './types'

function columnClause(column: ColumnInfo): string {
  const parts = [d.quoteIdent(column.name), column.dataType]

  if (column.collation && column.collation !== 'default') {
    parts.push(`COLLATE ${d.quoteIdent(column.collation)}`)
  }
  if (column.isAutoIncrement && column.defaultValue === null) {
    // Identity reads better than the serial pseudo-type it may have come from,
    // and is what Postgres itself recommends for new tables.
    parts.push('GENERATED BY DEFAULT AS IDENTITY')
  } else if (column.defaultValue !== null) {
    // Catalogue defaults are already SQL expressions, so they go in verbatim.
    parts.push(`DEFAULT ${column.defaultValue}`)
  }
  if (!column.isNullable) parts.push('NOT NULL')

  return parts.join(' ')
}

export function pgCreateTable(definition: TableDefinition): string {
  const body: string[] = []

  for (const column of [...definition.columns].sort((a, b) => a.ordinal - b.ordinal)) {
    body.push('  ' + columnClause(column))
  }

  const primary = definition.indexes.find((i) => i.type === 'PRIMARY')
  if (primary) {
    const cols = [...primary.columns]
      .sort((a, b) => a.seq - b.seq)
      .map((c) => d.quoteIdent(c.column))
      .join(', ')
    body.push(`  CONSTRAINT ${d.quoteIdent(primary.name)} PRIMARY KEY (${cols})`)
  }

  // A unique index that backs a constraint has to be declared as one, or the
  // rebuilt table would have the index but not the constraint.
  for (const index of definition.indexes) {
    if (index.type !== 'UNIQUE' || !index.isConstraint || index.columns.length === 0) continue
    const cols = [...index.columns]
      .sort((a, b) => a.seq - b.seq)
      .map((c) => d.quoteIdent(c.column))
      .join(', ')
    body.push(`  CONSTRAINT ${d.quoteIdent(index.name)} UNIQUE (${cols})`)
  }

  for (const fk of definition.foreignKeys) {
    const local = fk.columns.map((c) => d.quoteIdent(c.column)).join(', ')
    const remote = fk.columns.map((c) => d.quoteIdent(c.referencedColumn)).join(', ')
    let clause = `  CONSTRAINT ${d.quoteIdent(fk.name)} FOREIGN KEY (${local}) REFERENCES ${qualify(
      d,
      fk.referencedSchema,
      fk.referencedTable
    )} (${remote})`
    if (fk.onDelete && fk.onDelete !== 'NO ACTION') clause += ` ON DELETE ${fk.onDelete}`
    if (fk.onUpdate && fk.onUpdate !== 'NO ACTION') clause += ` ON UPDATE ${fk.onUpdate}`
    body.push(clause)
  }

  if (body.length === 0) return `-- ${definition.schema}.${definition.name} has no columns.`

  const target = qualify(d, definition.schema, definition.name)
  const statements = [`CREATE TABLE ${target} (\n${body.join(',\n')}\n);`]

  // Indexes and comments are separate statements in Postgres — they cannot ride
  // along inside CREATE TABLE the way MySQL's can.
  for (const index of definition.indexes) {
    if (index.type === 'PRIMARY' || index.isConstraint) continue
    const cols = [...index.columns]
      .sort((a, b) => a.seq - b.seq)
      .map((c) => d.quoteIdent(c.column))
      .join(', ')
    const unique = index.type === 'UNIQUE' ? 'UNIQUE ' : ''
    const using = index.storageType && index.storageType !== 'BTREE'
      ? ` USING ${index.storageType.toLowerCase()}`
      : ''
    statements.push(
      `CREATE ${unique}INDEX ${d.quoteIdent(index.name)} ON ${target}${using} (${cols});`
    )
  }

  if (definition.comment) {
    statements.push(`COMMENT ON TABLE ${target} IS ${d.stringLiteral(definition.comment)};`)
  }
  for (const column of definition.columns) {
    if (!column.comment) continue
    statements.push(
      `COMMENT ON COLUMN ${target}.${d.quoteIdent(column.name)} IS ${d.stringLiteral(
        column.comment
      )};`
    )
  }

  return statements.join('\n')
}
