/**
 * Turns the table designer's state into PostgreSQL DDL.
 *
 * The shape is what makes this a separate file from `./designerSql` rather than
 * a branch inside it. MySQL says everything in one `ALTER TABLE`'s
 * comma-separated clauses. Postgres cannot: a rename has to be a statement of
 * its own, indexes are `CREATE INDEX` rather than table clauses, and comments
 * are `COMMENT ON`. So this emits a *script*, and the order matters — renames
 * first so later statements can use the new names, the table rename last so
 * everything before it still refers to the old one.
 */

import type { DesignerColumn, DesignerForeignKey, DesignerIndex, DesignerState } from '@shared/types'
import { postgresDialect, qualify as qualifyWith } from '@shared/dialect'
import {
  designerFromDefinition,
  fkSignature,
  indexSignature,
  matchColumns,
  type NameMapper
} from './designerShared'

const d = postgresDialect
const q = (name: string): string => d.quoteIdent(name)
const lit = (value: string): string => d.stringLiteral(value)
const qualify = (schema: string | null | undefined, table: string): string =>
  qualifyWith(d, schema, table)

/** Defaults that are expressions or keywords, so they must not be quoted. */
const BARE_DEFAULTS =
  /^(NULL|TRUE|FALSE|CURRENT_TIMESTAMP|CURRENT_DATE|CURRENT_TIME|LOCALTIMESTAMP|NOW\(\)|-?\d+(\.\d+)?)$/i

function defaultExpression(value: string): string {
  const trimmed = value.trim()
  if (BARE_DEFAULTS.test(trimmed)) return trimmed
  // Already a literal, a call, or a parenthesised/cast expression — pass through.
  if (/^'.*'$/.test(trimmed) || /^\(.*\)$/.test(trimmed) || /^[A-Za-z_][\w.]*\s*\(/.test(trimmed)) {
    return trimmed
  }
  if (/::/.test(trimmed)) return trimmed
  return lit(trimmed)
}

/** The type as written, minus MySQL modifiers Postgres has no concept of. */
function dataType(column: DesignerColumn): string {
  return (column.dataType || 'varchar(255)').replace(/\s*\b(unsigned|zerofill)\b/gi, '').trim()
}

/**
 * A column as it appears inside CREATE TABLE or ADD COLUMN.
 *
 * `un`, `zf`, `b` and `charset` are deliberately ignored: Postgres has no
 * unsigned or zero-fill numerics, no per-column binary flag, and takes its
 * encoding from the database.
 */
export function columnDefinition(column: DesignerColumn): string {
  const parts = [q(column.name), dataType(column)]

  if (column.collation) parts.push(`COLLATE ${q(column.collation)}`)

  let sql = parts.join(' ')

  if (column.g && column.defaultValue.trim()) {
    // A generated column carries its expression instead of a default, and is
    // always STORED — Postgres has no VIRTUAL form.
    sql += ` GENERATED ALWAYS AS (${column.defaultValue.trim()}) STORED`
  } else if (column.ai) {
    // Identity supersedes serial; it is the standard spelling and the one
    // Postgres itself recommends.
    sql += ' GENERATED BY DEFAULT AS IDENTITY'
  } else if (column.defaultValue.trim()) {
    sql += ` DEFAULT ${defaultExpression(column.defaultValue)}`
  }

  if (column.nn) sql += ' NOT NULL'
  return sql
}

function indexColumnList(index: DesignerIndex): string {
  return index.columns
    .slice()
    .sort((a, b) => a.seq - b.seq)
    .map((c) => `${q(c.column)}${c.order === 'DESC' ? ' DESC' : ''}`)
    .join(', ')
}

/**
 * A unique index that exists to back a constraint has to be declared as the
 * constraint, not created as an index — that is the only form Postgres will
 * later let you drop, and `CREATE UNIQUE INDEX` would leave no constraint at all.
 */
function uniqueConstraint(index: DesignerIndex): string | null {
  if (!index.isConstraint || index.type !== 'UNIQUE' || index.columns.length === 0) return null
  return `CONSTRAINT ${q(index.name)} UNIQUE (${indexColumnList(index)})`
}

/** `CREATE INDEX` for a standalone index. PRIMARY and constraints are declared instead. */
function createIndex(schema: string, table: string, index: DesignerIndex): string | null {
  if (index.columns.length === 0 || index.type === 'PRIMARY') return null
  if (uniqueConstraint(index)) return null

  const unique = index.type === 'UNIQUE' ? 'UNIQUE ' : ''
  // FULLTEXT and SPATIAL have no Postgres equivalent; GIN and GiST are what you
  // would reach for instead, so those are what the storage type offers.
  const method =
    index.type === 'FULLTEXT' ? 'gin' : index.type === 'SPATIAL' ? 'gist' : index.storageType
  const using = method && method.toLowerCase() !== 'btree' ? ` USING ${method.toLowerCase()}` : ''

  let sql = `CREATE ${unique}INDEX ${q(index.name)} ON ${qualify(schema, table)}${using} (${indexColumnList(index)});`
  if (index.comment) {
    sql += `\nCOMMENT ON INDEX ${qualify(schema, index.name)} IS ${lit(index.comment)};`
  }
  return sql
}

function foreignKeyDefinition(fk: DesignerForeignKey): string | null {
  if (fk.skip || fk.columns.length === 0 || !fk.referencedTable) return null
  const local = fk.columns.map((c) => q(c.column)).join(', ')
  const remote = fk.columns.map((c) => q(c.referencedColumn)).join(', ')
  let sql = `CONSTRAINT ${q(fk.name)}\n    FOREIGN KEY (${local})\n    REFERENCES ${qualify(
    fk.referencedSchema,
    fk.referencedTable
  )} (${remote})`
  if (fk.onDelete) sql += `\n    ON DELETE ${fk.onDelete}`
  if (fk.onUpdate) sql += `\n    ON UPDATE ${fk.onUpdate}`
  return sql
}

/** `COMMENT ON` statements for the table and any commented column. */
function commentStatements(state: DesignerState, target: string): string[] {
  const out: string[] = []
  if (state.comment) out.push(`COMMENT ON TABLE ${target} IS ${lit(state.comment)};`)
  for (const column of state.columns) {
    if (!column.comment || !column.name.trim()) continue
    out.push(`COMMENT ON COLUMN ${target}.${q(column.name)} IS ${lit(column.comment)};`)
  }
  return out
}

export function buildCreateTable(state: DesignerState): string {
  const body: string[] = []

  for (const column of state.columns) {
    if (!column.name.trim()) continue
    body.push('  ' + columnDefinition(column))
  }

  const pkColumns = state.columns.filter((c) => c.pk && c.name.trim())
  const hasExplicitPrimary = state.indexes.some((i) => i.type === 'PRIMARY')
  if (pkColumns.length > 0 && !hasExplicitPrimary) {
    body.push(`  PRIMARY KEY (${pkColumns.map((c) => q(c.name)).join(', ')})`)
  }
  for (const index of state.indexes) {
    if (index.type !== 'PRIMARY' || index.columns.length === 0) continue
    body.push(`  PRIMARY KEY (${indexColumnList(index)})`)
  }

  for (const index of state.indexes) {
    const constraint = uniqueConstraint(index)
    if (constraint) body.push('  ' + constraint)
  }

  // A column ticked Unique gets its own constraint, unless an index already
  // covers it — otherwise re-creating a table read back from the server would
  // declare the same uniqueness twice.
  const constrainedColumns = new Set(
    state.indexes
      .filter((i) => i.type === 'UNIQUE' || i.type === 'PRIMARY')
      .flatMap((i) => i.columns.map((c) => c.column))
  )
  for (const column of state.columns) {
    if (column.uq && !column.pk && column.name.trim() && !constrainedColumns.has(column.name)) {
      body.push(`  CONSTRAINT ${q(`${column.name}_key`)} UNIQUE (${q(column.name)})`)
    }
  }

  for (const fk of state.foreignKeys) {
    const sql = foreignKeyDefinition(fk)
    if (sql) body.push('  ' + sql)
  }

  if (body.length === 0) return `-- Add at least one column before generating SQL.`

  const table = state.tableName || 'new_table'
  const target = qualify(state.schema, table)
  const statements = [`CREATE TABLE ${target} (\n${body.join(',\n')}\n);`]

  for (const index of state.indexes) {
    const sql = createIndex(state.schema, table, index)
    if (sql) statements.push(sql)
  }
  statements.push(...commentStatements(state, target))

  return statements.join('\n\n')
}

// ---------------------------------------------------------------------------
// ALTER
// ---------------------------------------------------------------------------

export function buildAlterTable(state: DesignerState): string {
  const original = state.original
  if (!original) return buildCreateTable(state)

  const target = qualify(original.schema, original.name)
  /** Statements that must stand alone, before the combined ALTER. */
  const before: string[] = []
  /** Comma-separated actions for the one combined ALTER TABLE. */
  const actions: string[] = []
  /** Standalone statements that run after it. */
  const after: string[] = []

  const originalDesigner = designerFromDefinition(original, 'postgres')
  const { matched, dropped, renamedBack } = matchColumns(state, originalDesigner)
  const canonical: NameMapper = (name) => renamedBack.get(name) ?? name

  // --- renames, first and on their own ---
  // Postgres refuses to combine RENAME with any other action, and doing them
  // first means every clause below can refer to the column's new name.
  for (const column of state.columns) {
    const previous = matched.get(column.key)
    if (previous && previous.name !== column.name) {
      before.push(`ALTER TABLE ${target} RENAME COLUMN ${q(previous.name)} TO ${q(column.name)};`)
    }
  }

  // --- columns ---
  for (const column of dropped) actions.push(`DROP COLUMN ${q(column.name)}`)

  for (const column of state.columns) {
    if (!column.name.trim()) continue
    const previous = matched.get(column.key)

    if (!previous) {
      // Postgres always appends; there is no FIRST/AFTER placement.
      actions.push(`ADD COLUMN ${columnDefinition(column)}`)
      continue
    }

    // Each facet of a column is altered separately, rather than restated in
    // full the way MySQL's CHANGE COLUMN does it.
    const type = dataType(column)
    if (type.toLowerCase() !== dataType(previous).toLowerCase()) {
      // The USING clause keeps casts that are not implicit — widening a varchar
      // needs none, but int -> text would fail without it.
      actions.push(`ALTER COLUMN ${q(column.name)} TYPE ${type} USING ${q(column.name)}::${type}`)
    }
    if (column.nn !== previous.nn) {
      actions.push(`ALTER COLUMN ${q(column.name)} ${column.nn ? 'SET' : 'DROP'} NOT NULL`)
    }
    if (column.defaultValue.trim() !== previous.defaultValue.trim() && !column.g) {
      actions.push(
        column.defaultValue.trim()
          ? `ALTER COLUMN ${q(column.name)} SET DEFAULT ${defaultExpression(column.defaultValue)}`
          : `ALTER COLUMN ${q(column.name)} DROP DEFAULT`
      )
    }
    if (column.ai !== previous.ai) {
      actions.push(
        column.ai
          ? `ALTER COLUMN ${q(column.name)} ADD GENERATED BY DEFAULT AS IDENTITY`
          : `ALTER COLUMN ${q(column.name)} DROP IDENTITY IF EXISTS`
      )
    }
  }

  // --- primary key ---
  // Compared by identity so renaming a PK column does not drop and re-add it.
  const originalPk = originalDesigner.columns.filter((c) => c.pk)
  const currentPk = state.columns.filter((c) => c.pk && c.name.trim())
  const originalPkKeys = originalPk.map((c) => c.key).join(',')
  const currentPkKeys = currentPk.map((c) => matched.get(c.key)?.key ?? c.key).join(',')
  if (originalPkKeys !== currentPkKeys) {
    const existing = originalDesigner.indexes.find((i) => i.type === 'PRIMARY')
    if (existing) actions.push(`DROP CONSTRAINT ${q(existing.name)}`)
    if (currentPk.length > 0) {
      actions.push(`ADD PRIMARY KEY (${currentPk.map((c) => q(c.name)).join(', ')})`)
    }
  }

  // --- indexes (PRIMARY handled above) ---
  const originalIndexes = new Map(
    originalDesigner.indexes.filter((i) => i.type !== 'PRIMARY').map((i) => [i.name, i])
  )
  const currentIndexes = new Map(
    state.indexes.filter((i) => i.type !== 'PRIMARY').map((i) => [i.name, i])
  )

  for (const [name, index] of originalIndexes) {
    const current = currentIndexes.get(name)
    if (current && indexSignature(current, canonical) === indexSignature(index)) continue
    if (index.isConstraint) {
      // Postgres refuses to DROP INDEX one that backs a constraint; the
      // constraint has to go, and takes its index with it.
      actions.push(`DROP CONSTRAINT ${q(name)}`)
    } else {
      // A plain index is schema-scoped in its own right, not owned by the table.
      after.push(`DROP INDEX ${qualify(original.schema, name)};`)
    }
  }
  for (const [name, index] of currentIndexes) {
    const previous = originalIndexes.get(name)
    if (previous && indexSignature(previous) === indexSignature(index, canonical)) continue
    const constraint = uniqueConstraint(index)
    if (constraint) {
      actions.push(`ADD ${constraint}`)
      continue
    }
    const sql = createIndex(state.schema, state.tableName || original.name, index)
    if (sql) after.push(sql)
  }

  // --- foreign keys ---
  const originalFks = new Map(originalDesigner.foreignKeys.map((f) => [f.name, f]))
  const currentFks = new Map(state.foreignKeys.filter((f) => !f.skip).map((f) => [f.name, f]))

  for (const [name, fk] of originalFks) {
    const current = currentFks.get(name)
    if (!current || fkSignature(current, canonical) !== fkSignature(fk)) {
      actions.push(`DROP CONSTRAINT ${q(name)}`)
    }
  }
  for (const [name, fk] of currentFks) {
    const previous = originalFks.get(name)
    if (!previous || fkSignature(previous) !== fkSignature(fk, canonical)) {
      const sql = foreignKeyDefinition(fk)
      if (sql) actions.push(`ADD ${sql}`)
    }
  }

  // --- comments ---
  if (state.comment !== original.comment) {
    after.push(`COMMENT ON TABLE ${target} IS ${state.comment ? lit(state.comment) : 'NULL'};`)
  }
  for (const column of state.columns) {
    if (!column.name.trim()) continue
    const previous = matched.get(column.key)
    if (previous && previous.comment === column.comment) continue
    if (!previous && !column.comment) continue
    after.push(
      `COMMENT ON COLUMN ${target}.${q(column.name)} IS ${
        column.comment ? lit(column.comment) : 'NULL'
      };`
    )
  }

  // --- table rename, last, so everything above still names the old table ---
  if (state.tableName && state.tableName !== original.name) {
    after.push(`ALTER TABLE ${target} RENAME TO ${q(state.tableName)};`)
  }
  if (state.schema && state.schema !== original.schema) {
    after.push(`ALTER TABLE ${target} SET SCHEMA ${q(state.schema)};`)
  }

  const statements = [...before]
  if (actions.length > 0) {
    statements.push(`ALTER TABLE ${target}\n${actions.map((a) => '  ' + a).join(',\n')};`)
  }
  statements.push(...after)

  if (statements.length === 0) return `-- No changes to apply to ${target}.`
  return statements.join('\n\n')
}

export function buildPostgresDesignerSql(state: DesignerState): string {
  return state.mode === 'create' ? buildCreateTable(state) : buildAlterTable(state)
}
